- README.md
- src/app/layout.tsx
- src/app/page.tsx
- src/styles/globals.css
- src/wording.json
Content Updates: integrated dynamic content from `wording.json` to populate sections with titles, descriptions, badges, and cards.
> feat: add wording.json

- src/app/[role]/televersement/page.tsx
- src/app/artisan/page.tsx
- src/app/bienvenue/page.tsx
- src/app/conseiller/page.tsx
- src/app/layout.tsx
- src/app/mandataire/page.tsx
- src/app/page.tsx
- src/app/particulier/page.tsx
- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.test.tsx
- src/components/Alert/Alert.tsx
- src/components/IconBackground/IconBackground.test.tsx
- src/components/Link/Link.test.tsx
- src/components/Link/Link.tsx
- src/components/Select/Select.stories.tsx
- src/components/Select/Select.test.tsx
- src/components/Select/Select.tsx
- src/components/Upload/Upload.stories.tsx
- src/components/Upload/Upload.test.tsx
- src/components/Upload/Upload.tsx
- src/components/index.ts
- src/styles/globals.css
- src/wording/wording.json
**Upload Page**: 
- Created a dedicated upload page for file uploads.
**Upload Component**: 
- Implemented the `Upload` component to handle file uploads.
- Added validation for file size and format.
- Included error handling to display messages for oversized files.
**Alert Component**: 
- Developed the `Alert` component to notify users about the confidentiality of submitted quotes.
- Provided additional information regarding the retention period of quotes.
**Select Component**: 
- Created the `Select` component for users to choose technical gestures related to the quote.
**Link Component Update**: 
- Updated the `Link` component to support new variants and improve usability.
**Wording Integration**: 
- Update `wording.json`
> add upload page

- next.config.ts
- package-lock.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/[role]/televersement/[id]/page.tsx
- src/app/[role]/televersement/page.tsx
- src/app/global-error.tsx
- src/components/Link/Link.test.tsx
- src/components/Link/Link.tsx
- src/components/Select/Select.tsx
- src/components/Upload/Upload.test.tsx
- src/components/Upload/Upload.tsx
Add Backend Data Integration to Upload Page
Upload Page Enhancements
- Implemented file upload functionality that allows users to select and upload files.
- Added validation to ensure that only files within the specified size limit (1 MB) are accepted. 50Mo in the next PR
- Displayed appropriate error messages when file uploads fail due to size restrictions.
Backend Data Integration
- Integrated API calls to send the uploaded files and associated data to the backend.
Testing
- Added unit tests for the upload component to ensure that all functionalities work as expected.
- Included tests for various scenarios, including valid file uploads, oversized files.
> add backend data to upload page

- src/app/[role]/televersement/[id]/page.tsx
- src/components/Accordion/Accordion.test.tsx
- src/components/Accordion/Accordion.tsx
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
- src/components/QuoteErrorCard/QuoteErrorCard.stories.tsx
- src/components/QuoteErrorCard/QuoteErrorCard.tsx
- src/components/QuoteErrorItem/QuoteErrorItem.test.tsx
- src/components/QuoteErrorItem/QuoteErrorItem.tsx
- src/wording/wording.json
> add mailto contact buttons

- src/app/page.tsx
- src/styles/globals.css
- src/utils/richTextParser.tsx
- src/wording/wording.json
PR en attendant de pouvoir push la complète https://github.com/betagouv/mon-devis-sans-oublis-frontend/pull/54
> fix landing page wording

- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.modal.content.ts
- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.modal.tsx
- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.tsx
- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.wording.ts
- src/page-sections/result/InvalidQuote.tsx
Ajout de la modale de partage (contenu en cours d'ajustement, une autre PR arrive avec le contenu formatté correctement)
> feat: add share modal & content

- .eslintrc.json
- src/app/debug/page.tsx
- src/components/Crisp/Crisp.tsx
- src/hooks/useCrisp.ts
- src/types/crisp.ts
Update de la page de debug pour matomo + fix & update lint
> feat: debug page + fix lint

- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.tsx
- src/hooks/useMatomo.ts
- src/lib/constants/matomoEvents.ts
-----
Dépends de https://github.com/MTES-MCT/mon-devis-sans-oublis-frontend/pull/142
----
Ajout de hook & constantes pour tracking Matomo
Ajout d'un tracking sur le clic du bouton "Exporter pour email"
> feat: matomo tracking

- .env.example
- README.md
- src/lib/config/env.config.ts
Petit correctif car j'ai oublié de prefixé APP_ENV par NEXT_PUBLIC du coup la variable n'est pas correctement récupérée
> fix: app_env next prefix

- src/app/debug/page.tsx
Petit update de la page de debug avec les helpers de check de l'environnement
> feat: update debug page

- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.wording.ts
- src/lib/constants/matomoEvents.ts
- src/wording/wording.json
Correction de label (e-mail) & suppression de wording en doublon (lié au fichiers wording dans le composant)
> fix: wording for email & useless texts

- src/page-sections/result/ResultClient.tsx
----
Dépends de https://github.com/MTES-MCT/mon-devis-sans-oublis-frontend/pull/144
---
Correction de l'affichage vide / incorrect lorsque le serveur n'a pas fini de traiter un fichier
Ajout d'un message fallback au bout de 20 tentatives avec 30 sec d'intervalles
> fix: polling & gestion du résultat d'upload devis

- src/app/bienvenue/page.tsx
correction du design de la page bienvenue (espace & fil ariane)
> fix: bienvenue design & add breadcrumb

- src/components/QuoteConformityCard/QuoteConformityCard.test.tsx
- src/page-sections/result/InvalidQuote.tsx
On masque le composant de conformité si 0 points de controles (ou négatif)
Ajout de tests sur le composant
> feat: masquer le composant de conformité si 0 ou pas de point de conformité + tests

- src/app/[profile]/televersement/[quoteCheckId]/page.tsx
- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.wording.ts
- src/hooks/useCrisp.ts
- src/lib/constants/matomoEvents.ts
- src/page-sections/result/ResultClient.tsx
Correction du wording exporter pour e-mail
Ajout d'un prompt Crisp sur la page de résultats au bout de 20 secondes
> feat: update wording & add crisp auto prompt

- src/app/[profile]/dossier/[quoteCaseId]/devis/[quoteCheckId]/page.tsx
- src/app/statistiques/page.tsx
- src/components/QuoteCaseConsistencyError/QuoteCaseConsistencyErrorTable.tsx
- src/components/QuoteSideMenu/QuoteSideMenu.tsx
- src/components/QuoteSideMenu/index.tsx
- src/hooks/useDeleteErrorReasons.ts
- src/page-sections/result/quoteCase/InvalidQuoteCase.tsx
- src/page-sections/result/quoteCheck/InvalidQuoteCheck.tsx
- src/page-sections/result/quoteCheck/ResultGestesClient.tsx
Ajout de la page détail d'un dossier dans un devis
Gestion de la sidebar + responsive
> feat: page détail devis dans dossier

- jest.setup.ts
- package-lock.json
- src/app/[profile]/dossier/[quoteCaseId]/modifier/page.tsx
- src/components/QuoteCaseConsistencyError/QuoteCaseConsistencyErrorTable.tsx
- src/components/QuoteSideMenu/QuoteSideMenu.tsx
- src/components/index.test.ts
- src/components/index.ts
- src/page-sections/result/quoteCase/InvalidQuoteCase.tsx
- src/page-sections/result/quoteCase/ResultAmpleurClient.tsx
- src/page-sections/result/quoteCase/ValidQuoteCase.tsx
- src/page-sections/upload/UploadClient.tsx
- src/types/quoteCheck.types.ts
- src/utils/mocks/quoteCase/quoteCase.invalid.mock.ts
Quelques modifications à savoir : 
- Fix de dépendances & update tests
- Suppression de l'icone "i" dans l'en-tête Erreurs de cohérences
- Affichage grisé pour les devis en FILE_ERROR dans la sidebar
- Affichage grisé pour les devis en FILE_ERROR dans la vue du dossier
- Ajout d'une Notice pour la présence de devis en FILE_ERROR dans la vue du dossier
- Correction de 2 bugs (Attempted to call useUserProfile() from the server but useUserProfile is on the client.) + upload réno par geste cas FILE ERROR qui redirigeait automatiquement
> feat: corrections & modification Rénovation d'ampleur

- src/components/Link/Link.tsx
- src/components/QuoteConformityCard/ProgressGauge.tsx
- src/components/QuoteConformityCard/QuoteConformityCard.tsx
- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.tsx
- src/components/QuoteErrorSharingCard/QuoteErrorSharingCard.wording.ts
- src/components/QuoteErrorTable/QuoteErrorTable.tsx
- src/page-sections/result/quoteCheck/InvalidQuoteCheck.tsx
- Correction du design responsive : 
- Fix erreur sur clé uniques dans QuoteErrorTable
- Fix warning sur Link
> feat: fix design 

- src/app/[profile]/televersement/renovation-ampleur/page.tsx
- src/page-sections/result/quoteCase/ResultAmpleurClient.tsx
Modification du bouton d'upload en réno d'ampleur : 
- Désactivation bouton
- Traitement en background pour fluidifer
> feat: upload reno ampleur isSubmitting & background treatment

- src/actions/__tests__/dataChecks.actions.test.ts
- src/actions/dataChecks.actions.ts
- src/app/rge/page.tsx
- src/page-sections/rge/RgeForm.tsx
- src/page-sections/rge/RgePageClient.tsx
- src/page-sections/rge/RgeResult.tsx
- src/types/api.types.ts
- src/types/dataChecks.types.ts
Ajout d'une page de vérification RGE à partir du SIRET / RGE / Date :
> feat: ajout d'une page de vérification RGE

- README.md
- src/actions/__tests__/dataChecks.actions.test.ts
- src/actions/dataChecks.actions.ts
- src/components/DropdownCheckboxList/DropdownCheckboxList.tsx
- src/page-sections/rge/RgeForm.tsx
- src/page-sections/rge/RgePageClient.tsx
- src/page-sections/rge/RgeResult.tsx
- src/types/dataChecks.types.ts
- src/utils/rge/rge.utils.ts
- MAJ de la page de consultation RGE avec gestion des gestes en input
- MAJ appels API
- MAJ Tests
- MAJ des résultats groupés par gestes
> feat: maj de la page RGE avec selection des gestes

- src/app/statistiques/page.tsx
> fix: url with https

- sentry.server.config.ts
Update du monitoring en utilisant des setImmediate pour non bloquant
> chore: non blocking monitoring using setImmediate
